### ISSUE TITLE
Issues with checkpoint files

### ISSUE THREAD

**Issue by RitikGandhi21** [JerrySchonenberg/CloudGAN#2]
Can you please fix the checkpoint files? I believe there is some issue with it

**Comment by JerrySchonenberg** [comment]
Hi Ritik, thanks for your issue. So I've taken a look at the checkpoint files and it appears that for the option `--weights_GAN [GAN_checkpoint]` you should link to the directory for SN_PatchGAN instead of to `checkpoint` (as the readme indicates). 

Hope this helps!
